export const apiRoutesMap = {
  authLogin: '/auth/login',
  authRegister: '/auth/register',
  authLogout: '/auth/logout',
  authResetPassword: '/auth/reset-password',
  authForgotPassword: '/auth/forgot-password',
  authResendEmailVerification: '/email/verification-notification',
  authVerifyEmail: '/email/verify',
  auth2faVerify: '/2fa/verify',
  auth2faSetup: '/2fa/setup',
  auth2faDisable: '/2fa/disable',
  me: '/me',
  users: '/users',
  projects: '/projects',
  tasks: '/tasks',
  tenants: '/tenants',
  tenantsPreview: '/tenants/preview',
  contractors: '/contractors',
  expenses: '/expenses',
  invoices: '/invoices',
  products: '/products',
  tags: '/tags',
  skills: '/skills',
  contractorAddresses: '/contractors/:contractorId/addresses',
  contractorContacts: '/contractors/:contractorId/contacts',
  contractorBankAccounts: '/contractors/:contractorId/bank-accounts',
  feeds: '/feeds',
}

export const apiRoutes = {
  authLogin: () => apiRoutesMap.authLogin,
  authLogout: () => apiRoutesMap.authLogout,
  projects: () => apiRoutesMap.projects,
  tasks: () => apiRoutesMap.tasks,
  tenants: () => apiRoutesMap.tenants,
  tenantsPreview: () => apiRoutesMap.tenantsPreview,
  tenantsSwitch: (tenantId: string) => `/tenants/${tenantId}/switch`,
  contractors: () => apiRoutesMap.contractors,
  invoices: () => apiRoutesMap.invoices,
  products: () => apiRoutesMap.products,
  tags: () => apiRoutesMap.tags,
  skills: () => apiRoutesMap.skills,
  feeds: () => apiRoutesMap.feeds,
}
