name: Lint, Type Check, and Tests

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '.docs/**'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '.docs/**'
  workflow_dispatch:

jobs:
  lint-typecheck:
    name: Lint, Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint --fix
        run: pnpm lint-fix

      - name: Commit ESLint fixes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: auto eslint fixes" && git push origin ${{ steps.get_branch.outputs.branch_name }}

      - name: Run Type Check
        run: pnpm tsc --noEmit

      # - name: Run Tests
      #   run: pnpm vitest run
      #   env:
      #     NODE_ENV: test

      - name: Run Build
        run: pnpm build
