name: Build & Deploy Vue App

on:
  workflow_dispatch:  # ręczne uruchamianie
  push:
    branches:
      - main           # automatycznie przy push na main

permissions:
  contents: read       # potrzebne do checkout repo

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    outputs:
      build-artifact: ${{ steps.upload.outputs.artifact-path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate version.json
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{ \"commit\": \"$COMMIT_HASH\", \"buildDate\": \"$BUILD_DATE\" }" > public/version.json

      - name: Build app
        run: pnpm build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_API_MOCK: ${{ vars.VITE_API_MOCK }}
          VITE_CHAT_ENABLED: ${{ vars.VITE_CHAT_ENABLED }}
          VITE_AI_CHAT_ENABLED: ${{ vars.VITE_AI_CHAT_ENABLED }}
          VITE_OAUTH_GOOGLE: ${{ vars.VITE_OAUTH_GOOGLE }}
          VITE_PUSHER_APP_KEY: ${{ secrets.VITE_PUSHER_APP_KEY }}
          VITE_PUSHER_HOST: ${{ secrets.VITE_PUSHER_HOST }}
          VITE_PUSHER_PORT: 443
          VITE_PUSHER_SCHEME: https
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.VITE_STRIPE_PUBLISHABLE_KEY }}

      - name: Upload dist as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy App
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'dist/*'
          target: ${{ secrets.SSH_TARGET }}
          strip_components: 1
